# Generated by Django 3.2.9 on 2021-11-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mymode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMode',
        ),
    ]
